sudo: required
language: python
python:
  - '2.7'

services:
  - docker

install: 
  - docker build -t assimilator .
  - docker run -d -p 443:443/tcp --name assimilator assimilator

before_script:
  - pip install -r requirements.txt

script:
  - docker ps | grep assimilator 
  - py.test tests

after_success:
- if [ "$TRAVIS_BRANCH" == "docker" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push videlanicolas/assimilator;
  fi

deploy:
  provider: releases
  api_key:
    secure: "k3HoiFinpkRNeT/VY7uGIpG6Q56vMC85zcGjCIM3ZR74YiwEV/a5kV4BLHIvQPvD7ONSxPn2C/XubaMcRAH2Re0yHLzH6dD/gfEYMJmUsHRIT3NHkgsYH2hyNiAISsu99QxYbTI03ajSIZDta5XL+PUYUTr5i/lKUM9iFNwkdaegYdirQ/mB1WiA8xlbA/wFB5rvMjkXuQ0/BsW+XdUIA73o1mDFwd2iFuCByY0r14YAbgglxxD38yboZ8RIteCf++iB6quzVqS+7+hiqB179BOp+6nL0yq5FJVEqz8VLItSL5dwFq90qq0zEtMzhr0sQ7YFSMEuNsT/87NN7H1AlBc01FGFxH/wRHbbI4VR6dhxE1mhFXOuqYRjzgXEgHcmOO6bkedBfi32XSUAVoV1S3n6iWcJz7i7JZyl3U2BKje/oZkObl6CPU09yzYAlaUrroMya9ULn9fGIvq6G3Drs469Rh4nUxWfBMqdyYb0OdbpNR/8iWG6/7Z8irWtNtXkrvQsDtpoqcRmhihyPCmFWi76VuP2hEMrUchSufkVhP589oZ33AZjHYtEAkWkrODAdPk40C03jFgQUf6BQf5Xo6rJA39BR1+cNtqZECQ0GbfqZHkGXzA58bAV/kvfqgoAKB0gd/TAxbdisYxqjQzcHauT+a3lXMQC26GXt5niD8M="
  skip_cleanup: true
  on:
    repo: videlanicolas/assimilator
    tags: true
