sudo: required
language: python
python:
  - '2.7'

services:
  - docker

install: 
  - docker build -t assimilator .
  - docker run -d -p 443:443/tcp --name assimilator assimilator

before_script:
  - pip install -r requirements.txt

script:
  - docker ps | grep assimilator 
  - py.test tests

after_success:
- if [ "$TRAVIS_BRANCH" == "docker" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push videlanicolas/assimilator;
  fi

deploy:
  provider: releases
  api_key:
    secure: "KBXbfaajhjplkD0UD8dA7GLVKc4nmMR5VBgqsncyw8aH71LbMsR9Z1MYjjvfCSvzm056dVWTg/w5mDVea62jzDtqSuFvzhAEp5Q23y6Bh4rftoB6ACVNqcQjSwFAm5M2edAed0bgk8U9mI1e9u3b5MWv9hiRT+Mz0j5C6yhwzEbtp23gwC8SwlF9S6WpadcogBSVE/IKxDASL2Nqf2YICIcq0ODAm1cqzR88ETu/ZTLKeL/S0mCBIPvn8xj3JhrjqZPLCPZAbX18IjIbXtAp9Kq+3hbYSfn/ifMlUD5R3J0A8cj4voye+DaalL3+x8kYwuTOF5QKlR1VyaTRhfaV4MTgHhILjGCe0HXFbx0hm8eWLlnjznnTOEgroTWEKQf1t7PGRk9HGgIbsZ3TooxZ97WFgGZkX4voYL8klnOmUKEVUkePY+elM2vs+d4Z00L/aliSQPE4e5vsdvu8vYNFR8hAl/lkDwJ4Oi4kRmEC4/HiWHuC9d8cigFu6VhIe1UIm5jWwna5X44CsOlVTf8Rhfqj0BFX1it8d1KUFcqnpBqCEJ0mOdLcitFFVcmEUSJlo73LWn32FNCQvZJWAonogFbOiLpBoISi1Shd0zzbw14q7WaMIhGfN2b57XdoCi16xrBO0yloDBImd0MeZhfX6UkIXPMJv/1Ko6bOnuEE3xc="
  skip_cleanup: true
  on:
    repo: videlanicolas/assimilator
    tags: true
