sudo: required
language: python
python:
  - '2.7'

services:
  - docker

install: 
  - docker build -t assimilator .
  - docker run -d -p 443:443/tcp --name assimilator assimilator

before_script:
  - pip install -r requirements.txt

script:
  - docker ps | grep -q assimilator 
  - py.test tests

after_success:
- if [ "$TRAVIS_BRANCH" == "docker" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push videlanicolas/assimilator;
  fi